import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import { resolveWorkflowPath } from '../utils/workflow';
import { parseWorkflowMetadata } from '../utils/knime-parser';
import { getAllFiles } from '../utils/fs';
import AdmZip from 'adm-zip';

export const reportCommand = new Command('report')
  .description('Génère un rapport détaillé (Markdown) du workflow')
  .requiredOption('-w, --workflow <name>', 'Nom du workflow')
  .option('-p, --path <path>', 'Chemin du dossier de recherche', '.')
  .option('-o, --output <file>', 'Fichier de sortie', 'REPORT.md')
  .action(async (options: any) => {
    const spinner = ora(`Génération du rapport pour ${chalk.cyan(options.workflow)}...`).start();

    try {
      const target = resolveWorkflowPath(options.workflow, options.path);
      const isDir = target.workflowArg === '-workflowDir';

      let xmlData = '';
      if (isDir) {
        xmlData = fs.readFileSync(path.join(target.targetPath, 'workflow.knime'), 'utf8');
      } else {
        const zip = new AdmZip(target.targetPath);
        const knimeEntry = zip.getEntries().find((e: any) => e.entryName.endsWith('workflow.knime'));
        if (knimeEntry) xmlData = zip.readAsText(knimeEntry);
      }

      if (!xmlData) throw new Error('Workflow metadata not found.');

      const metadata = parseWorkflowMetadata(xmlData, options.workflow);
      
      let report = `# Workflow Report: ${metadata.name}\n\n`;
      report += `## General Information\n`;
      report += `- **Author:** ${metadata.author}\n`;
      report += `- **KNIME Version:** ${metadata.version}\n`;
      report += `- **Description:** ${metadata.description || 'N/A'}\n\n`;

      report += `## Statistics\n`;
      report += `- **Nodes:** ${metadata.nodes.length}\n`;
      report += `- **Connections:** ${metadata.connections.length}\n`;
      report += `- **Workflow Variables:** ${metadata.variables.length}\n`;
      report += `- **Required Bundles:** ${metadata.bundles.length}\n\n`;

      report += `## Nodes List\n`;
      metadata.nodes.forEach(n => {
        report += `- [${n.id}] ${n.name}\n`;
      });
      report += `\n`;

      if (metadata.variables.length > 0) {
        report += `## Workflow Variables\n`;
        report += `| Name | Type | Value |\n`;
        report += `| --- | --- | --- |\n`;
        metadata.variables.forEach(v => {
          report += `| ${v.name} | ${v.type} | ${v.value} |\n`;
        });
        report += `\n`;
      }

      if (metadata.bundles.length > 0) {
        report += `## Required Extensions (Bundles)\n`;
        metadata.bundles.forEach(b => {
          report += `- ${b.name} (${b.version})\n`;
        });
        report += `\n`;
      }

      if (isDir) {
        const allFiles = getAllFiles(target.targetPath);
        const largeFiles = allFiles.filter(f => f.size > 10 * 1024 * 1024); // > 10MB
        if (largeFiles.length > 0) {
          report += `## Warnings (Large Files)\n`;
          largeFiles.forEach(f => {
            const relPath = path.relative(target.targetPath, f.path);
            report += `- \`${relPath}\` (${(f.size / 1024 / 1024).toFixed(2)} MB)\n`;
          });
          report += `\n`;
        }
      }

      report += `---\n*Generated by KNIME CLI on ${new Date().toLocaleString()}*\n`;

      fs.writeFileSync(options.output, report);
      spinner.succeed(chalk.green(`Rapport généré avec succès : ${chalk.bold(options.output)}`));

    } catch (err: any) {
      spinner.fail(chalk.red(`Erreur lors de la génération du rapport : ${err.message}`));
      process.exit(1);
    }
  });
